
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const SET_CART_QUANTITY = 'SET_CART_QUANTITY';

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const CLEAR_ORDER_STATE= 'CLEAR_ORDER_STATE';


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_PRICE_FILTER = 'SET_PRICE_FILTER';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';


export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const FETCH_ALLS_ORDERS_REQUEST = 'FETCH_ALLS_ORDERS_REQUEST';
export const FETCH_ALLS_ORDERS_SUCCESS = 'FETCH_ALLS_ORDERS_SUCCESS';
export const FETCH_ALLS_ORDERS_FAILURE = 'FETCH_ALLS_ORDERS_FAILURE';
export const UPDATE_ORDER_STATE_SUCCESS = 'UPDATE_ORDER_STATE_SUCCESS';
export const UPDATE_ORDER_STATE_FAILURE = 'UPDATE_ORDER_STATE_FAILURE';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';

export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';

export const SB_CREATE_REQUEST = 'SB_CREATE_REQUEST';
export const SB_CREATE_SUCCESS = 'SB_CREATE_SUCCESS';
export const SB_CREATE_FAIL = 'SB_CREATE_FAIL';

export const FETCH_LATEST_ORDER_REQUEST = 'FETCH_LATEST_ORDER_REQUEST';
export const FETCH_LATEST_ORDER_SUCCESS = 'FETCH_LATEST_ORDER_SUCCESS';
export const FETCH_LATEST_ORDER_FAILURE = 'FETCH_LATEST_ORDER_FAILURE';

export const FETCH_SB_REQUEST = 'FETCH_SB_REQUEST';
export const FETCH_SB_SUCCESS = 'FETCH_SB_SUCCESS';
export const FETCH_SB_FAILURE = 'FETCH_SB_FAILURE';

export const SET_SUBCATEGORY_FILTER = 'SET_SUBCATEGORY_FILTER';

// ===============================
// 🏦 TAXXA ACTION TYPES
// ===============================

// 👤 BUYER ACTIONS
export const FETCH_BUYER_REQUEST = 'FETCH_BUYER_REQUEST';
export const FETCH_BUYER_SUCCESS = 'FETCH_BUYER_SUCCESS';
export const FETCH_BUYER_FAILURE = 'FETCH_BUYER_FAILURE';
export const CREATE_BUYER_REQUEST = 'CREATE_BUYER_REQUEST';
export const CREATE_BUYER_SUCCESS = 'CREATE_BUYER_SUCCESS';
export const CREATE_BUYER_FAILURE = 'CREATE_BUYER_FAILURE';

// 🏢 SELLER ACTIONS
export const FETCH_SELLER_REQUEST = 'FETCH_SELLER_REQUEST';
export const FETCH_SELLER_SUCCESS = 'FETCH_SELLER_SUCCESS';
export const FETCH_SELLER_FAILURE = 'FETCH_SELLER_FAILURE';
export const CREATE_SELLER_REQUEST = 'CREATE_SELLER_REQUEST';
export const CREATE_SELLER_SUCCESS = 'CREATE_SELLER_SUCCESS';
export const CREATE_SELLER_FAILURE = 'CREATE_SELLER_FAILURE';
export const UPDATE_SELLER_REQUEST = 'UPDATE_SELLER_REQUEST';
export const UPDATE_SELLER_SUCCESS = 'UPDATE_SELLER_SUCCESS';
export const UPDATE_SELLER_FAILURE = 'UPDATE_SELLER_FAILURE';

// 📋 BILL ACTIONS
export const GENERATE_BILL_REQUEST = 'GENERATE_BILL_REQUEST';
export const GENERATE_BILL_SUCCESS = 'GENERATE_BILL_SUCCESS';
export const GENERATE_BILL_FAILURE = 'GENERATE_BILL_FAILURE';
export const FETCH_BILLS_REQUEST = 'FETCH_BILLS_REQUEST';
export const FETCH_BILLS_SUCCESS = 'FETCH_BILLS_SUCCESS';
export const FETCH_BILLS_FAILURE = 'FETCH_BILLS_FAILURE';
export const FETCH_BILL_BY_ID_REQUEST = 'FETCH_BILL_BY_ID_REQUEST';
export const FETCH_BILL_BY_ID_SUCCESS = 'FETCH_BILL_BY_ID_SUCCESS';
export const FETCH_BILL_BY_ID_FAILURE = 'FETCH_BILL_BY_ID_FAILURE';

// 🧾 INVOICE ACTIONS
export const SEND_INVOICE_REQUEST = 'SEND_INVOICE_REQUEST';
export const SEND_INVOICE_SUCCESS = 'SEND_INVOICE_SUCCESS';
export const SEND_INVOICE_FAILURE = 'SEND_INVOICE_FAILURE';
export const GET_ALL_INVOICES_REQUEST = 'GET_ALL_INVOICES_REQUEST';
export const GET_ALL_INVOICES_SUCCESS = 'GET_ALL_INVOICES_SUCCESS';
export const GET_ALL_INVOICES_FAILURE = 'GET_ALL_INVOICES_FAILURE';
export const GET_INVOICE_BY_ID_REQUEST = 'GET_INVOICE_BY_ID_REQUEST';
export const GET_INVOICE_BY_ID_SUCCESS = 'GET_INVOICE_BY_ID_SUCCESS';
export const GET_INVOICE_BY_ID_FAILURE = 'GET_INVOICE_BY_ID_FAILURE';

// 💳 CREDIT NOTE ACTIONS
export const CREATE_CREDIT_NOTE_REQUEST = 'CREATE_CREDIT_NOTE_REQUEST';
export const CREATE_CREDIT_NOTE_SUCCESS = 'CREATE_CREDIT_NOTE_SUCCESS';
export const CREATE_CREDIT_NOTE_FAILURE = 'CREATE_CREDIT_NOTE_FAILURE';

// 🌍 DIAN CATALOG ACTIONS
export const FETCH_COUNTRIES_REQUEST = 'FETCH_COUNTRIES_REQUEST';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE';
export const FETCH_DEPARTMENTS_REQUEST = 'FETCH_DEPARTMENTS_REQUEST';
export const FETCH_DEPARTMENTS_SUCCESS = 'FETCH_DEPARTMENTS_SUCCESS';
export const FETCH_DEPARTMENTS_FAILURE = 'FETCH_DEPARTMENTS_FAILURE';
export const FETCH_MUNICIPALITIES_REQUEST = 'FETCH_MUNICIPALITIES_REQUEST';
export const FETCH_MUNICIPALITIES_SUCCESS = 'FETCH_MUNICIPALITIES_SUCCESS';
export const FETCH_MUNICIPALITIES_FAILURE = 'FETCH_MUNICIPALITIES_FAILURE';

// 🔧 TAXXA UTILITY ACTIONS
export const CLEAR_TAXXA_STATE = 'CLEAR_TAXXA_STATE';
export const SET_TAXXA_LOADING = 'SET_TAXXA_LOADING';
export const SET_TAXXA_ERROR = 'SET_TAXXA_ERROR'; 
export const CLEAR_MANUAL_INVOICE_DATA = 'CLEAR_MANUAL_INVOICE_DATA';
export const CREATE_MANUAL_INVOICE_FAILURE = 'CREATE_MANUAL_INVOICE_FAILURE';
export const CREATE_MANUAL_INVOICE_REQUEST = 'CREATE_MANUAL_INVOICE_REQUEST';
export const CREATE_MANUAL_INVOICE_SUCCESS = 'CREATE_MANUAL_INVOICE_SUCCESS';
export const GET_MANUAL_INVOICE_DATA_FAILURE = 'GET_MANUAL_INVOICE_DATA_FAILURE';
export const GET_MANUAL_INVOICE_DATA_REQUEST = 'GET_MANUAL_INVOICE_DATA_REQUEST';
export const GET_MANUAL_INVOICE_DATA_SUCCESS = 'GET_MANUAL_INVOICE_DATA_SUCCESS';

// ===============================
// 📦 STOCK MANAGEMENT ACTION TYPES
// ===============================

// Dashboard
export const FETCH_DASHBOARD_REQUEST = 'FETCH_DASHBOARD_REQUEST';
export const FETCH_DASHBOARD_SUCCESS = 'FETCH_DASHBOARD_SUCCESS';
export const FETCH_DASHBOARD_FAILURE = 'FETCH_DASHBOARD_FAILURE';

// Stock Operations
export const ADD_STOCK_REQUEST = 'ADD_STOCK_REQUEST';
export const ADD_STOCK_SUCCESS = 'ADD_STOCK_SUCCESS';
export const ADD_STOCK_FAILURE = 'ADD_STOCK_FAILURE';

export const REMOVE_STOCK_REQUEST = 'REMOVE_STOCK_REQUEST';
export const REMOVE_STOCK_SUCCESS = 'REMOVE_STOCK_SUCCESS';
export const REMOVE_STOCK_FAILURE = 'REMOVE_STOCK_FAILURE';

export const ADJUST_STOCK_REQUEST = 'ADJUST_STOCK_REQUEST';
export const ADJUST_STOCK_SUCCESS = 'ADJUST_STOCK_SUCCESS';
export const ADJUST_STOCK_FAILURE = 'ADJUST_STOCK_FAILURE';

// Stock History
export const FETCH_STOCK_HISTORY_REQUEST = 'FETCH_STOCK_HISTORY_REQUEST';
export const FETCH_STOCK_HISTORY_SUCCESS = 'FETCH_STOCK_HISTORY_SUCCESS';
export const FETCH_STOCK_HISTORY_FAILURE = 'FETCH_STOCK_HISTORY_FAILURE';

// Stock Alerts
export const FETCH_LOW_STOCK_REQUEST = 'FETCH_LOW_STOCK_REQUEST';
export const FETCH_LOW_STOCK_SUCCESS = 'FETCH_LOW_STOCK_SUCCESS';
export const FETCH_LOW_STOCK_FAILURE = 'FETCH_LOW_STOCK_FAILURE';

export const FETCH_OUT_OF_STOCK_REQUEST = 'FETCH_OUT_OF_STOCK_REQUEST';
export const FETCH_OUT_OF_STOCK_SUCCESS = 'FETCH_OUT_OF_STOCK_SUCCESS';
export const FETCH_OUT_OF_STOCK_FAILURE = 'FETCH_OUT_OF_STOCK_FAILURE';

// Stock Filters
export const SET_STOCK_SECTION_FILTER = 'SET_STOCK_SECTION_FILTER';
export const SET_STOCK_STATUS_FILTER = 'SET_STOCK_STATUS_FILTER';
export const CLEAR_STOCK_FILTERS = 'CLEAR_STOCK_FILTERS';

// Categories CRUD
export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE';

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

// SubCategories CRUD
export const FETCH_SUBCATEGORIES_REQUEST = 'FETCH_SUBCATEGORIES_REQUEST';
export const FETCH_SUBCATEGORIES_SUCCESS = 'FETCH_SUBCATEGORIES_SUCCESS';
export const FETCH_SUBCATEGORIES_FAILURE = 'FETCH_SUBCATEGORIES_FAILURE';

export const CREATE_SUBCATEGORY_REQUEST = 'CREATE_SUBCATEGORY_REQUEST';
export const CREATE_SUBCATEGORY_SUCCESS = 'CREATE_SUBCATEGORY_SUCCESS';
export const CREATE_SUBCATEGORY_FAILURE = 'CREATE_SUBCATEGORY_FAILURE';

export const UPDATE_SUBCATEGORY_REQUEST = 'UPDATE_SUBCATEGORY_REQUEST';
export const UPDATE_SUBCATEGORY_SUCCESS = 'UPDATE_SUBCATEGORY_SUCCESS';
export const UPDATE_SUBCATEGORY_FAILURE = 'UPDATE_SUBCATEGORY_FAILURE';

export const DELETE_SUBCATEGORY_REQUEST = 'DELETE_SUBCATEGORY_REQUEST';
export const DELETE_SUBCATEGORY_SUCCESS = 'DELETE_SUBCATEGORY_SUCCESS';
export const DELETE_SUBCATEGORY_FAILURE = 'DELETE_SUBCATEGORY_FAILURE';
